// interpreter.
Public void Interpret_C(String __fnName, Symbol* __args) {
    switch ( Get_Fn_Index(__fnName) ) {
        case 0: { _Out(b8); _Arg(b8*,boolean);
            *c_out = Toggle(boolean);
        } break;
        case 1: { _Out(b8); _Arg(u8*,min); _Arg(u8*,x); _Arg(u8*,max);
            *c_out = Is_In_Bounds(min, x, max);
        } break;
        case 2: { _Arg(u8*,dest); _Arg(u8*,src); _Arg(u32,size);
            Mem_Copy_Backward(dest, src, size);
        } break;
        case 3: { _Arg(u8*,dest); _Arg(u8*,src); _Arg(u32,size);
            Mem_Copy_Forward(dest, src, size);
        } break;
        case 4: { _Out(u32); _Arg(u8*,mem); _Arg(u32,size); _Arg(u8*,bytesToFind); _Arg(u32,sizeBytes); _Arg(u32,timesToIgnore);
            *c_out = FindAnyDiffByteForward(mem, size, bytesToFind, sizeBytes, timesToIgnore);
        } break;
        case 5: { _Out(u8*); _Arg(u8*,mem); _Arg(u8*,end); _Arg(u8*,bytesToFind); _Arg(u32,sizeBytes); _Arg(u32,timesToIgnore);
            *c_out = FindAnyDiffByteBackward(mem, end, bytesToFind, sizeBytes, timesToIgnore);
        } break;
        case 6: { _Out(u32); _Arg(u8*,mem); _Arg(u32,count); _Arg(u8*,bytesToFind); _Arg(u32,byteCount); _Arg(u32,timesToIgnore);
            *c_out = FindAnyByteForwardTimes(mem, count, bytesToFind, byteCount, timesToIgnore);
        } break;
        case 7: { _Out(u32); _Arg(u8*,mem); _Arg(u8*,end); _Arg(u8*,bytesToFind); _Arg(u32,sizeBytes); _Arg(u32,timesToIgnore);
            *c_out = FindAnyByteBackward(mem, end, bytesToFind, sizeBytes, timesToIgnore);
        } break;
        case 8: { _Out(u32); _Arg(u8*,mem); _Arg(u8*,end); _Arg(uint8_t,byteToFind); _Arg(u32,timesToIgnore);
            *c_out = FindByteForwardTimes(mem, end, byteToFind, timesToIgnore);
        } break;
        case 9: { _Out(u32); _Arg(u8*,mem); _Arg(u32,size); _Arg(uint8_t,byteToFind); _Arg(u32,timesToIgnore);
            *c_out = FindByteBackwardsTimes(mem, size, byteToFind, timesToIgnore);
        } break;
        case 10: { _Arg(u8*,mem); _Arg(u32,size); _Arg(uint8_t,value);
            Mem_Fill_With_Byte(mem, size, value);
        } break;
        case 11: { _Out(s32); _Arg(u8*,mem1); _Arg(u8*,mem2); _Arg(u32,size);
            *c_out = Mem_Comp(mem1, mem2, size);
        } break;
        case 12: { _Out(b8); _Arg(u8*,inMem1); _Arg(u8*,inMem2); _Arg(u32,inSize);
            *c_out = Mem_Equal(inMem1, inMem2, inSize);
        } break;
        case 13: { _Out(b8); _Arg(u8*,mem); _Arg(u32,size);
            *c_out = Mem_Equal_Zero(mem, size);
        } break;
        case 14: {
            Mem_Init();
        } break;
        case 15: { _Arg(Memory_Arena*,arena); _Arg(u8*,base); _Arg(u32,capacity);
            Arena_Create(arena, base, capacity);
        } break;
        case 16: { _Out(Memory_Arena); _Arg(Memory_Arena*,parent); _Arg(u32,capacity);
            *c_out = Arena_Create_From_Arena(parent, capacity);
        } break;
        case 17: { _Arg(Memory_Arena*,arena);
            Arena_Clear(arena);
        } break;
        case 18: { _Out(u8*); _Arg(Memory_Arena*,arena); _Arg(u32,size);
            *c_out = Arena_Alloc(arena, size);
        } break;
        case 19: { _Arg(Memory_Arena*,arena); _Arg(Memory_Arena,src);
            Arena_Push_Arena(arena, src);
        } break;
        case 20: { _Arg(Log_Type,type); _Arg(CString,fmt);
            Log(type, fmt);
        } break;
        case 21: { _Out(String); _Arg(Memory_Arena*,arena); _Arg(u32,count);
            *c_out = Str_Alloc(arena, count);
        } break;
        case 22: { _Out(u32); _Arg(String,string); _Arg(String,chars);
            *c_out = Str_Find_Any_Char_Backward(string, chars);
        } break;
        case 23: { _Out(u32); _Arg(String,str); _Arg(u8,character);
            *c_out = Str_Find_Diff_Char_Forward(str, character);
        } break;
        case 24: { _Out(u32); _Arg(String,str); _Arg(String,chars);
            *c_out = Str_Find_Any_Diff_Char_Forward(str, chars);
        } break;
        case 25: { _Out(u32); _Arg(String,str); _Arg(u8,inChar);
            *c_out = Str_Find_Char_Forward(str, inChar);
        } break;
        case 26: { _Arg(String*,dst); _Arg(String,src);
            Str_Copy(dst, src);
        } break;
        case 27: { _Arg(String*,str);
            Str_Null_Terminate(str);
        } break;
        case 28: { _Out(String); _Arg(Memory_Arena*,arena); _Arg(String,src); _Arg(b8,shouldPutNullTerminator);
            *c_out = Str_Alloc_And_Copy(arena, src, shouldPutNullTerminator);
        } break;
        case 29: { _Out(u32); _Arg(String,string); _Arg(u8,charToFind); _Arg(u32,timesToIgnore);
            *c_out = Str_Find_Char_Backward_Times(string, charToFind, timesToIgnore);
        } break;
        case 30: { _Out(u32); _Arg(String,string); _Arg(u8,charToFind);
            *c_out = Str_Find_Char_Backward(string, charToFind);
        } break;
        case 31: { _Out(b8); _Arg(CString,str1); _Arg(CString,str2); _Arg(u32,count);
            *c_out = CStr_Size_Equal(str1, str2, count);
        } break;
        case 32: { _Out(String); _Arg(String,string); _Arg(u32,count);
            *c_out = Str_Begin(string, count);
        } break;
        case 33: { _Out(String); _Arg(String,string); _Arg(u32,count);
            *c_out = Str_End(string, count);
        } break;
        case 34: { _Out(String); _Arg(String,string); _Arg(u32,skip);
            *c_out = Str_Skip_Begin(string, skip);
        } break;
        case 35: { _Out(String); _Arg(String,string); _Arg(u32,skip);
            *c_out = Str_Skip_End(string, skip);
        } break;
        case 36: { _Out(u8*); _Arg(u8*,min); _Arg(u8*,x); _Arg(u8*,max);
            *c_out = Check_Bounds(min, x, max);
        } break;
        case 37: { _Out(String); _Arg(String,string); _Arg(u8*,ptr);
            *c_out = Str_Begin_Ptr(string, ptr);
        } break;
        case 38: { _Out(b8); _Arg(u8*,str1); _Arg(u8*,str2); _Arg(u32,count);
            *c_out = Chars_Equal(str1, str2, count);
        } break;
        case 39: { _Out(b8); _Arg(u8*,ptr); _Arg(String,str);
            *c_out = Chars_Ptr_Equal(ptr, str);
        } break;
        case 40: { _Out(s32); _Arg(CString,str1); _Arg(CString,str2);
            *c_out = CStr_Comp(str1, str2);
        } break;
        case 41: { _Out(b8); _Arg(CString,str1); _Arg(CString,str2);
            *c_out = CStr_Equal(str1, str2);
        } break;
        case 42: { _Out(u32); _Arg(CString,str);
            *c_out = CStr_Len(str);
        } break;
        case 43: { _Out(String); _Arg(CString,str);
            *c_out = CStr_To_Str(str);
        } break;
        case 44: { _Out(s32); _Arg(String,str1); _Arg(String,str2);
            *c_out = Str_Comp(str1, str2);
        } break;
        case 45: { _Out(b8); _Arg(String,str1); _Arg(String,str2);
            *c_out = Str_Equal(str1, str2);
        } break;
        case 46: { _Out(b8); _Arg(String,a); _Arg(String,b);
            *c_out = Str_Begin_Equal(a, b);
        } break;
        case 47: { _Out(b8); _Arg(String,a); _Arg(String,b);
            *c_out = Str_End_Equal(a, b);
        } break;
        case 48: { _Out(u32); _Arg(String,src); _Arg(String,match);
            *c_out = Str_Find_Str_Forward(src, match);
        } break;
        case 49: { _Out(String); _Arg(String,src); _Arg(String,match); _Arg(b8,shouldAdvanceMatch);
            *c_out = Str_Consume(src, match, shouldAdvanceMatch);
        } break;
        case 50: { _Arg(String*,strOut); _Arg(String,str1); _Arg(String,str2);
            CatStr(strOut, str1, str2);
        } break;
        case 51: { _Out(String); _Arg(String,path);
            *c_out = Str_Get_File_Name_In_Path(path);
        } break;
        case 52: { _Arg(u16*,inStr16); _Arg(u32,inSize); _Arg(u8*,outStr8);
            Str_16_To_8(inStr16, inSize, outStr8);
        } break;
        case 53: { _Arg(String*,dst); _Arg(String,src);
            Str_Push(dst, src);
        } break;
        case 54: { _Arg(String*,dst); _Arg(u8,ch);
            Str_Push_Char(dst, ch);
        } break;
        case 55: { _Out(b8); _Arg(Array_String,strs); _Arg(String,str);
            *c_out = Array_String_Exists(strs, str);
        } break;
        case 56: { _Out(u32); _Arg(u32,value); _Arg(b8*,isExact);
            *c_out = Log2(value, isExact);
        } break;
        case 57: { _Out(f32); _Arg(f32,degrees);
            *c_out = Radians(degrees);
        } break;
        case 58: { _Arg(u32,stdhandleToGet); _Arg(String,string); _Arg(u8,color);
            ConsoleWrite(stdhandleToGet, string, color);
        } break;
        case 59: { _Arg(Log_Type,logType); _Arg(CString,fmt);
            Win32_Log(logType, fmt);
        } break;
        case 60: { _Out(u8*); _Arg(size_t,inSize);
            *c_out = OS_Alloc_Mem(inSize);
        } break;
        case 61: { _Out(u8*); _Arg(size_t,inSize); _Arg(u8*,inAddress);
            *c_out = OS_Alloc_Mem_At(inSize, inAddress);
        } break;
        case 62: { _Arg(u8*,inMem);
            OS_Free_Mem(inMem);
        } break;
        case 63: { _Out(u8*); _Arg(u32*,dataTag); _Arg(u32,tag); _Arg(u8*,retVar);
            *c_out = Poly_(dataTag, tag, retVar);
        } break;
        case 64: { _Out(u8*); _Arg(Memory_Arena*,arena); _Arg(Array_void*,array); _Arg(u32,elemSize);
            *c_out = DArray_Expand(arena, array, elemSize);
        } break;
        case 65: { _Out(b8); _Arg(Ring_Buffer_void*,ringBuffer); _Arg(u8*,elem); _Arg(u32,elemSize);
            *c_out = Ring_Buffer_Push_Impl(ringBuffer, elem, elemSize);
        } break;
        case 66: { _Out(b8); _Arg(Ring_Buffer_void*,ringBuffer); _Arg(u8*,outElem); _Arg(u32,elemSize);
            *c_out = Ring_Buffer_Pop_Impl(ringBuffer, outElem, elemSize);
        } break;
        case 67: { _Out(u8*); _Arg(void**,ioPtr); _Arg(u32,inSize);
            *c_out = Consume(ioPtr, inSize);
        } break;
        case 68: { _Out(u8*); _Arg(u8*,inBase); _Arg(u32,inSize); _Arg(u32*,ioOffset);
            *c_out = Consume_Offset(inBase, inSize, ioOffset);
        } break;
        case 69: { _Out(String_Scan); _Arg(u8*,scan); _Arg(u8*,end);
            *c_out = StrScan(scan, end);
        } break;
        case 70: { _Out(String_Scan); _Arg(String,string);
            *c_out = Str_Scan_From_Str(string);
        } break;
        case 71: { _Out(String); _Arg(String,src); _Arg(String,fmt);
            *c_out = Str_Parse_And_Consume_Fmt_Impl(src, fmt);
        } break;
        case 72: { _Arg(String_Scan*,strScan); _Arg(u32,charCount);
            StrScanAdvance(strScan, charCount);
        } break;
        case 73: { _Out(b8); _Arg(String_Scan,strScan);
            *c_out = StrScanEOS(strScan);
        } break;
        case 74: { _Out(u16); _Arg(u64,inValue);
            *c_out = Get_Digit_Count(inValue);
        } break;
        case 75: { _Out(b8); _Arg(String,str);
            *c_out = Str_Is_Integer(str);
        } break;
        case 76: { _Out(String); _Arg(u32,value);
            *c_out = U32_To_Str(value);
        } break;
        case 77: { _Out(s64); _Arg(String,string);
            *c_out = Str_To_S64(string);
        } break;
        case 78: { _Out(f32); _Arg(String,string);
            *c_out = StrToF32(string);
        } break;
        case 79: { _Out(u8*); _Arg(u8*,base); _Arg(u8*,ptr);
            *c_out = Abs_To_Rel_Ptr(base, ptr);
        } break;
        case 80: { _Out(u8*); _Arg(u8*,base); _Arg(u8*,ptr);
            *c_out = Rel_To_Abs_Ptr(base, ptr);
        } break;
        case 81: { _Out(String); _Arg(File_String,inFileString);
            *c_out = Str_From_File_Str(inFileString);
        } break;
        case 82: { _Out(File_String); _Arg(String,str);
            *c_out = File_String_From_Str(str);
        } break;
        case 83: {
            Time_OS_Init();
        } break;
        case 84: {
            Time_OS_Cleanup();
        } break;
        case 85: { _Out(u64);
            *c_out = Time_Get();
        } break;
        case 86: { _Out(u64);
            *c_out = Time_CPU_Counter();
        } break;
        case 87: { _Out(s64);
            *c_out = Time_OS_Counter();
        } break;
        case 88: { _Out(f32); _Arg(s64,begin); _Arg(s64,end);
            *c_out = Time_OS_Seconds_Elapsed(begin, end);
        } break;
        case 89: { _Out(f32); _Arg(f32,secs);
            *c_out = Time_Sec_To_Ms(secs);
        } break;
        case 90: { _Out(u64); _Arg(FILETIME,inFileTime);
            *c_out = OS_FILETIME_To_Time(inFileTime);
        } break;
        case 91: { _Out(u64); _Arg(u64,time);
            *c_out = Time_Mask_Days(time);
        } break;
        case 92: { _Out(u64); _Arg(u64,time);
            *c_out = Time_Mask_Hrs(time);
        } break;
        case 93: { _Out(u64); _Arg(u64,time);
            *c_out = Time_Mask_Mins(time);
        } break;
        case 94: { _Out(u64); _Arg(u64,time);
            *c_out = Time_Mask_Secs(time);
        } break;
        case 95: { _Out(u64); _Arg(u64,time);
            *c_out = Time_Mask_Mils(time);
        } break;
        case 96: { _Out(b8); _Arg(CString,dirPath);
            *c_out = File_Exists(dirPath);
        } break;
        case 97: { _Out(File_Handle); _Arg(CString,path);
            *c_out = File_Create(path);
        } break;
        case 98: { _Out(File_Handle); _Arg(CString,path);
            *c_out = File_Open(path);
        } break;
        case 99: { _Out(b8); _Arg(File_Handle,inHandle);
            *c_out = File_Handle_Is_Valid(inHandle);
        } break;
        case 100: { _Arg(File_Handle,handle);
            File_Close(handle);
        } break;
        case 101: { _Out(b8); _Arg(CString,path);
            *c_out = File_Delete(path);
        } break;
        case 102: { _Out(u32); _Arg(File_Handle,retHandle);
            *c_out = File_Get_Size(retHandle);
        } break;
        case 103: { _Out(u64); _Arg(CString,inPath);
            *c_out = File_Get_Write_Time(inPath);
        } break;
        case 104: { _Out(b8); _Arg(File_Handle,handle); _Arg(u32,bytesToRead); _Arg(u8*,mem);
            *c_out = File_Read(handle, bytesToRead, mem);
        } break;
        case 105: { _Out(b8); _Arg(File_Handle,handle); _Arg(size_t,offset); _Arg(u32,bytesToRead); _Arg(u8*,mem);
            *c_out = File_Read_At(handle, offset, bytesToRead, mem);
        } break;
        case 106: { _Out(u8*); _Arg(String,path); _Arg(Memory_Arena*,arena); _Arg(u32*,size);
            *c_out = File_Read_All(path, arena, size);
        } break;
        case 107: { _Out(b8); _Arg(File_Handle,handle); _Arg(u32,bytesToWrite); _Arg(u8*,mem);
            *c_out = File_Write(handle, bytesToWrite, mem);
        } break;
        case 108: { _Out(b8); _Arg(File_Handle,handle); _Arg(size_t,offset); _Arg(u32,bytesToWrite); _Arg(u8*,mem);
            *c_out = File_Write_At(handle, offset, bytesToWrite, mem);
        } break;
        case 109: { _Arg(File_Handle,handle);
            File_Clear(handle);
        } break;
        case 110: { _Arg(File_Handle,handle); _Arg(u32,size);
            File_Size_Set(handle, size);
        } break;
        case 111: { _Arg(String,path); _Arg(u8*,data); _Arg(u32,size);
            File_Create_With_Contents(path, data, size);
        } break;
        case 112: { _Out(b8); _Arg(String,path); _Arg(u8*,data); _Arg(u32,size);
            *c_out = File_Replace_Contents(path, data, size);
        } break;
        case 113: { _Out(b8); _Arg(CString,dirPath);
            *c_out = Dir_Exists(dirPath);
        } break;
        case 114: { _Out(b8); _Arg(CString,dirPath);
            *c_out = Dir_Create(dirPath);
        } break;
        case 115: { _Arg(String,inDirPath);
            Dir_Recursive_Delete(inDirPath);
        } break;
        case 116: { _Out(b8); _Arg(CString,dirPath); _Arg(File_Info*,infos); _Arg(u32,DEBUGCount);
            *c_out = Dir_Get_All_Files_Write_Times(dirPath, infos, DEBUGCount);
        } break;
        case 117: { _Out(File_Tag); _Arg(CString,path);
            *c_out = File_Get_Tag(path);
        } break;
        case 118: { _Out(b8); _Arg(String,inDirPath); _Arg(Dir_Stream*,outDirStream);
            *c_out = Dir_Stream_Open(inDirPath, outDirStream);
        } break;
        case 119: { _Out(b8); _Arg(Dir_Stream*,inDirStream); _Arg(String*,outFileName);
            *c_out = Dir_Stream_Read(inDirStream, outFileName);
        } break;
        case 120: { _Arg(Dir_Stream*,inDirStream);
            Dir_Stream_Close(inDirStream);
        } break;
        case 121: { _Arg(String,inDirPath); _Arg(Dir_Monitor*,outMonitor);
            Dir_Monitor_Init(inDirPath, outMonitor);
        } break;
        case 122: { _Out(b8); _Arg(Dir_Monitor*,inMonitor); _Arg(HANDLE,reloadSemaphore); _Arg(Dir_Change*,outDirChange);
            *c_out = Dir_Monitor_Wait_Till_Change(inMonitor, reloadSemaphore, outDirChange);
        } break;
        case 123: { _Arg(Dir_Monitor*,inMonitor);
            Dir_Monitor_End(inMonitor);
        } break;
        case 124: { _Arg(String,path); _Arg(u8*,data); _Arg(u32,size);
            File_Fill_With_Contents_Safe(path, data, size);
        } break;
        case 125: { _Out(b8); _Arg(File_Handle,handle); _Arg(u32,bytesToAppend); _Arg(u8*,mem);
            *c_out = File_Append(handle, bytesToAppend, mem);
        } break;
        case 126: { _Out(File_Handle); _Arg(CString,path); _Arg(b8,async);
            *c_out = Dir_Open(path, async);
        } break;
        case 127: { _Out(u32); _Arg(String,dirPath);
            *c_out = Dir_File_Count(dirPath);
        } break;
        case 128: { _Out(b8); _Arg(String,dirPath); _Arg(String,fileName);
            *c_out = Dir_Find_File(dirPath, fileName);
        } break;
        case 129: { _Out(Type*); _Arg(Symbol*,parent); _Arg(String,name);
            *c_out = Type_Get_Unsafe(parent, name);
        } break;
        case 130: { _Out(Type*); _Arg(String,name);
            *c_out = Type_Get(name);
        } break;
        case 131: { _Out(Type*); _Arg(String,name);
            *c_out = Type_All_Get(name);
        } break;
        case 132: { _Out(Symbol*); _Arg(Symbol*,parent); _Arg(String,name); _Arg(Type*,type);
            *c_out = Symbol_Create(parent, name, type);
        } break;
        case 133: { _Out(Symbol*); _Arg(String,name);
            *c_out = Symbol_Scope_Get(name);
        } break;
        case 134: { _Out(Symbol*); _Arg(Symbol*,parent); _Arg(String,name);
            *c_out = Symbol_Get(parent, name);
        } break;
        case 135: { _Out(Symbol*); _Arg(Symbol*,parent); _Arg(String,name);
            *c_out = Symbol_Get_Unsafe(parent, name);
        } break;
        case 136: { _Out(Symbol*); _Arg(Symbol*,symbol);
            *c_out = Addr(symbol);
        } break;
        case 137: { _Out(Symbol*); _Arg(Symbol*,symbol); _Arg(Type*,type); _Arg(b8,allocNew); _Arg(u8*,mem);
            *c_out = Symbol_Set(symbol, type, allocNew, mem);
        } break;
        case 138: { _Out(Symbol_Unit*); _Arg(Symbol*,parent); _Arg(String,name); _Arg(b8,inExternLocals);
            *c_out = Symbol_Unit_Get_Unsafe_(parent, name, inExternLocals);
        } break;
        case 139: { _Out(Symbol_Unit*); _Arg(Symbol*,parent); _Arg(String,name);
            *c_out = Symbol_Unit_Get(parent, name);
        } break;
        case 140: { _Out(Symbol_Unit*); _Arg(Symbol*,symbol); _Arg(Symbol_Unit,unit);
            *c_out = Symbol_Push_Child_C_(symbol, unit);
        } break;
        case 141: { _Out(Symbol*); _Arg(u32,index);
            *c_out = Scope_Top(index);
        } break;
        case 142: { _Out(Symbol*);
            *c_out = Module_Top();
        } break;
        case 143: { _Out(u8*); _Arg(u32,size);
            *c_out = Symbol_Data_Create(size);
        } break;
        case 144: { _Out(Symbol*); _Arg(Symbol*,parent); _Arg(String,name); _Arg(b8,isPerm);
            *c_out = Symbol_New_(parent, name, isPerm);
        } break;
        case 145: { _Arg(Symbol*,symbol); _Arg(u8*,mem);
            Symbol_Set_Mem(symbol, mem);
        } break;
        case 146: { _Arg(Symbol*,symbol); _Arg(Type*,type);
            Symbol_Create_From_Type(symbol, type);
        } break;
        case 147: { _Out(Symbol*); _Arg(Symbol*,parent); _Arg(String,name); _Arg(b8,isPerm); _Arg(Type*,type); _Arg(b8,allocNew); _Arg(u8*,mem);
            *c_out = Symbol_Create_And_Init_(parent, name, isPerm, type, allocNew, mem);
        } break;
        case 148: { _Out(u8*); _Arg(Symbol*,symbol);
            *c_out = Symbol_Data_Get(symbol);
        } break;
        case 149: { _Out(u8*); _Arg(Type*,type); _Arg(Symbol*,symbol);
            *c_out = Symbol_Data_Get_And_Check(type, symbol);
        } break;
        case 150: { _Arg(String,name); _Arg(Param,ret); _Arg(Array_Param,params); _Arg(Array_Fn_Call_P,code);
            Fn_Create(name, ret, params, code);
        } break;
        case 151: { _Out(Parser_State); _Arg(Memory_Arena*,arena); _Arg(String,text);
            *c_out = Parser_Init(arena, text);
        } break;
        case 152: { _Out(Parser_State); _Arg(String,path); _Arg(Memory_Arena*,arena);
            *c_out = Parser_Init_From_File(path, arena);
        } break;
        case 153: { _Arg(Parser_State*,state);
            Parse_Symbol(state);
        } break;
        case 154: { _Out(Wea_File_Tag); _Arg(String,name);
            *c_out = Wea_File_Tag_Get_From_String(name);
        } break;
        case 155: { _Out(Wea_File_Info); _Arg(String,path);
            *c_out = Parse_Wea_File_Info(path);
        } break;
        case 156: { _Out(Array_Fn_Call_P); _Arg(Parser_State*,state); _Arg(Wea_File_Tag,tag);
            *c_out = Parse(state, tag);
        } break;
        case 157: { _Out(Array_Fn_Call_P); _Arg(String,text); _Arg(Wea_File_Tag,tag);
            *c_out = Parse_Text(text, tag);
        } break;
        case 158: { _Out(Array_Fn_Call_P); _Arg(String,path);
            *c_out = Parse_File(path);
        } break;
        case 159: { _Out(Fn*); _Arg(String,path);
            *c_out = Module_Create_By_File(path);
        } break;
        case 160: { _Out(Symbol*); _Arg(Code*,code);
            *c_out = Scope_Iter_Advance(code);
        } break;
        case 161: {
            Interpret_Begin();
        } break;
        case 162: {
            Interpret_End();
        } break;
        case 163: { _Out(Symbol*); _Arg(Array_Shared,sharedList); _Arg(Symbol*,args);
            *c_out = Get_Out_Symbol(sharedList, args);
        } break;
        case 164: { _Out(Symbol*); _Arg(Fn_Call*,fnCall);
            *c_out = Get_Out_Symbol_Fn_Call(fnCall);
        } break;
        case 165: { _Arg(Symbol*,wFnCall); _Arg(Symbol_Unit*,outArg);
            Fn_Call_Resolve(wFnCall, outArg);
        } break;
        case 166: { _Arg(Symbol*,wFnCall); _Arg(Symbol_Unit*,outArg);
            Fn_Call_Resolve_Rec(wFnCall, outArg);
        } break;
        case 167: { _Out(Symbol*); _Arg(Code,code); _Arg(Symbol_Unit*,outArg);
            *c_out = Interpret(code, outArg);
        } break;
        case 168: { _Out(Symbol*); _Arg(Array_Fn_Call_P,code);
            *c_out = Interpret_Code(code);
        } break;
        case 169: { _Out(Symbol*); _Arg(Code_Block*,codeBlock);
            *c_out = Interpret_Code_Block(codeBlock);
        } break;
        case 170: { _Out(Symbol*); _Arg(Symbol*,wFnCall);
            *c_out = Interpret_Fn_Call(wFnCall);
        } break;
        case 171: { _Out(u32); _Arg(String,name);
            *c_out = Get_Fn_Index(name);
        } break;
        case 172: { _Out(Raw_Fn*); _Arg(String,name);
            *c_out = Get_C_Fn(name);
        } break;
        case 173: { _Out(Raw_Type*); _Arg(String,name);
            *c_out = Raw_Type_Get(name);
        } break;
        case 174: { _Arg(String,typeName); _Arg(String,name); _Any(init);
            Let(typeName, name, init);
        } break;
        case 175: { _Arg(String,typeName); _Arg(String,name); _Arg(Symbol*,scope);
            Let_C(typeName, name, scope);
        } break;
        case 176: { _Arg(String,name);
            Using(name);
        } break;
        case 177: { _Out(b8); _Arg(String,typeName);
            *c_out = Type_Name_Is_Integer(typeName);
        } break;
        case 178: { _Out(b8); _Arg(String,typeName);
            *c_out = Type_Name_Is_Raw_Data(typeName);
        } break;
        case 179: { _Out(b8); _Arg(String,typeName);
            *c_out = Type_Name_Is_Pointer(typeName);
        } break;
        case 180: { _Out(b8); _Arg(String,typeName);
            *c_out = Type_Name_Is_Array(typeName);
        } break;
        case 181: { _Out(b8); _Arg(String,typeName);
            *c_out = Type_Name_Is_WArray(typeName);
        } break;
        case 182: { _Out(b8); _Arg(String,typeName);
            *c_out = Type_Name_Is_Sym(typeName);
        } break;
        case 183: { _Out(b8); _Arg(String,typeName);
            *c_out = Type_Name_Is_Primitive(typeName);
        } break;
        case 184: { _Out(b8); _Arg(Type*,type);
            *c_out = Type_Is_Primitive(type);
        } break;
        case 185: { _Out(b8); _Arg(Type*,type);
            *c_out = Type_Is_Not_Primitive(type);
        } break;
        case 186: { _Out(Type*); _Arg(Symbol*,parent); _Arg(String,name);
            *c_out = Type_Create(parent, name);
        } break;
        case 187: { _Out(u32); _Arg(Type*,type);
            *c_out = Type_Size(type);
        } break;
        case 188: { _Out(b8); _Arg(Type*,a); _Arg(Type*,b);
            *c_out = Type_Check(a, b);
        } break;
        case 189: { _Arg(Type*,type); _Arg(Array_Raw_Field,rawFields);
            Bundle_Init(type, rawFields);
        } break;
        case 190: { _Out(Type*); _Arg(String,name); _Arg(Array_Raw_Field,rawFields);
            *c_out = Bundle_Create(name, rawFields);
        } break;
        case 191: { _Arg(Type*,type); _Arg(Array_Raw_Field,rawFields);
            Union_Init(type, rawFields);
        } break;
        case 192: { _Arg(String,name); _Arg(Array_Raw_Field,rawFields);
            Union_Create(name, rawFields);
        } break;
        case 193: { _Out(Symbol*); _Arg(Type*,type);
            *c_out = Symbol_Enum_Values(type);
        } break;
        case 194: { _Arg(Type*,type); _Arg(Array_String,names);
            Enum_Init(type, names);
        } break;
        case 195: { _Arg(String,name); _Arg(Array_String,names);
            Enum_Create(name, names);
        } break;
        case 196: { _Out(String); _Arg(String,ptrName);
            *c_out = Pointee_Name(ptrName);
        } break;
        case 197: { _Arg(Type*,type); _Arg(Type*,pointee);
            Pointer_Init(type, pointee);
        } break;
        case 198: { _Arg(Type*,type); _Arg(String,name);
            Integer_Init_By_Name(type, name);
        } break;
        case 199: { _Arg(Type*,type); _Arg(String,name);
            Raw_Data_Init_By_Name(type, name);
        } break;
        case 200: { _Arg(Type*,type); _Arg(Type*,elemType);
            Array_Init(type, elemType);
        } break;
        case 201: { _Arg(Type*,type); _Arg(Type*,elemType);
            WArray_Init(type, elemType);
        } break;
        case 202: { _Out(String); _Arg(String,name);
            *c_out = Elem_Name(name);
        } break;
        case 203: { _Out(String); _Arg(String,name);
            *c_out = Handle_Pointer(name);
        } break;
        case 204: { _Out(String); _Arg(String,name);
            *c_out = WElem_Name(name);
        } break;
        case 205: { _Out(Type*); _Arg(Symbol*,parent); _Arg(String,name);
            *c_out = Type_Primitive_Create_By_Name(parent, name);
        } break;
        case 206: { _Out(b8); _Arg(String,name);
            *c_out = Type_Exists(name);
        } break;
        case 207: { _Out(Type*); _Arg(Type*,type);
            *c_out = Type_Ptr_Get(type);
        } break;
        case 208: { _Out(b8); _Arg(Enum*,_enum); _Arg(Symbol*,valueSymbol);
            *c_out = Exists_Enum_Val(_enum, valueSymbol);
        } break;
        case 209: { _Out(b8); _Arg(Array_Shared,sharedList);
            *c_out = Has_Optional(sharedList);
        } break;
        case 210: { _Out(b8); _Arg(Array_Shared,sharedList);
            *c_out = Has_Variadic(sharedList);
        } break;
        case 211: { _Out(Type*); _Arg(String,name);
            *c_out = Type_Create_Temp(name);
        } break;
        case 212: { _Out(Type*); _Arg(String,name);
            *c_out = Type_Get_Temp(name);
        } break;
        case 213: { _Arg(Type*,type); _Arg(String,name);
            Type_Init_Temp(type, name);
        } break;
        case 214: { _Out(Fn*); _Arg(String,name);
            *c_out = Symbol_Get_Module(name);
        } break;
        case 215: { _Out(Symbol*);
            *c_out = Symbol_Core();
        } break;
        case 216: { _Out(Symbol_Unit*); _Arg(String,name);
            *c_out = Symbol_Unit_Scope_Get(name);
        } break;
        case 217: { _Out(b8); _Arg(Symbol*,parent); _Arg(String,name);
            *c_out = Symbol_Exists(parent, name);
        } break;
        case 218: { _Out(b8); _Arg(Symbol*,parent); _Arg(String,name); _Arg(Type*,type);
            *c_out = Symbol_Check_Type(parent, name, type);
        } break;
        case 219: { _Out(Symbol*); _Arg(String,name);
            *c_out = Get_Sym(name);
        } break;
        case 220: { _Out(Symbol*); _Arg(String,name);
            *c_out = Get_Sym_Unsafe(name);
        } break;
        case 221: { _Out(Symbol*); _Arg(Symbol*,parent); _Arg(String,name);
            *c_out = Symbol_Forward(parent, name);
        } break;
        case 222: { _Out(Symbol*); _Arg(Symbol*,child);
            *c_out = Symbol_Backward(child);
        } break;
        case 223: { _Out(Symbol*); _Arg(Symbol*,symbol);
            *c_out = Symbol_Inner(symbol);
        } break;
        case 224: { _Out(Symbol*); _Arg(Symbol*,symbol);
            *c_out = Symbol_Outer(symbol);
        } break;
        case 225: { _Out(Symbol*); _Arg(Symbol*,symbol);
            *c_out = Deref(symbol);
        } break;
        case 226: { _Out(b8); _Arg(Symbol*,symbol);
            *c_out = Symbol_Data_Is_In_Data_Arena(symbol);
        } break;
        case 227: { _Out(Symbol*); _Arg(Type*,type); _Arg(u8*,data);
            *c_out = Symbol_Lit_Create(type, data);
        } break;
        case 228: { _Out(Symbol*); _Arg(String,str);
            *c_out = Wea_Str_Lit(str);
        } break;
        case 229: { _Out(Symbol*); _Arg(Symbol*,symbol);
            *c_out = WLit(symbol);
        } break;
        case 230: { _Arg(Symbol*,symbol); _Arg(Array_Field,fields);
            Symbol_Create_From_Fields(symbol, fields);
        } break;
        case 231: { _Arg(Symbol*,symbol);
            Symbol_Resolve(symbol);
        } break;
        case 232: { _Out(b8); _Arg(Symbol*,symbol); _Arg(Type*,type);
            *c_out = Are_Symbol_And_Type_Compatible(symbol, type);
        } break;
        case 233: { _Out(Fn*); _Arg(Symbol*,parent); _Arg(String,name); _Arg(Param,ret); _Arg(Array_Param,params); _Arg(Array_Fn_Call_P,code); _Arg(b8,shouldCreateLocals);
            *c_out = Fn_Create_(parent, name, ret, params, code, shouldCreateLocals);
        } break;
        case 234: { _Out(Fn*); _Arg(Symbol*,parent); _Arg(String,name); _Arg(Param,ret); _Arg(Array_Param,params); _Arg(Array_Fn_Call_P,code);
            *c_out = Fn_Create_With_Locals(parent, name, ret, params, code);
        } break;
        case 235: { _Arg(u32,scope); _Arg(String,name); _Arg(Param,ret); _Arg(Array_Param,params); _Arg(Array_Fn_Call_P,code);
            Fn_Create_Scope(scope, name, ret, params, code);
        } break;
        case 236: { _Out(Fn*); _Arg(String,name); _Arg(Array_Fn_Call_P,code);
            *c_out = Module_Create(name, code);
        } break;
        case 237: { _Out(Symbol*); _Arg(Fn_Call*,fnCall);
            *c_out = Get_Fn_Call_Symbol(fnCall);
        } break;
        case 238: { _Out(Symbol*); _Arg(Symbol_Unit,fn); _Arg(Array_Symbol_Unit,inUnits);
            *c_out = F_(fn, inUnits);
        } break;
        case 239: { _Out(Symbol*); _Arg(String,fnName); _Arg(Array_Symbol_Unit,inUnits);
            *c_out = F_By_Name(fnName, inUnits);
        } break;
        case 240: {
            Symbol_Init();
        } break;
        case 241: { _Arg(Parser_State*,state);
            Lexer_Parse(state);
        } break;
        case 242: { _Out(b8); _Arg(Parser_State*,state);
            *c_out = Parser_Is_EoF(state);
        } break;
        case 243: { _Out(Token*); _Arg(Parser_State*,state); _Arg(u32,tokenID);
            *c_out = Lexer_Advance_To_Index(state, tokenID);
        } break;
        case 244: { _Out(Token*); _Arg(Parser_State*,state);
            *c_out = Lexer_Advance(state);
        } break;
        case 245: { _Out(Token*); _Arg(Parser_State*,state); _Arg(Token_Tag,tag);
            *c_out = Lexer_Advance_And_Check(state, tag);
        } break;
        case 246: { _Arg(Parser_State*,state);
            Lexer_Update_Parser_Line(state);
        } break;
        case 247: { _Out(Token*); _Arg(Parser_State*,state); _Arg(u32,index);
            *c_out = Lexer_Look_Back(state, index);
        } break;
        case 248: { _Out(Token*); _Arg(Parser_State*,state); _Arg(u32,index);
            *c_out = Lexer_Look_Ahead(state, index);
        } break;
        case 249: { _Arg(Parser_State*,state);
            Lexer_Consume_White_Space(state);
        } break;
        case 250: { _Out(String); _Arg(Parser_State*,state);
            *c_out = Parser_Parse_String(state);
        } break;
        case 251: { _Out(b8); _Arg(Symbol*,argSymbol);
            *c_out = Is_Symbol_Fn(argSymbol);
        } break;
        case 252: { _Out(Symbol_Unit); _Arg(Symbol*,argSymbol);
            *c_out = Set_Default_Arg(argSymbol);
        } break;
        case 253: { _Out(Symbol*); _Arg(Parser_State*,state);
            *c_out = Parse_Symbol_L(state);
        } break;
        case 254: { _Out(Symbol*); _Arg(Parser_State*,state);
            *c_out = Parse_Arg(state);
        } break;
        case 255: { _Out(Symbol_Unit); _Arg(Parser_State*,state); _Arg(Symbol**,outSymbol);
            *c_out = Parse_Arg_Unit(state, outSymbol);
        } break;
        case 256: { _Out(Symbol*); _Arg(String,name); _Arg(Symbol**,parent);
            *c_out = Symbol_Scope_Exists(name, parent);
        } break;
        case 257: { _Arg(String,typeName); _Arg(String,name); _Any(init); _Arg(Symbol*,scope);
            Let_(typeName, name, init, scope);
        } break;
        case 258: { _Arg(String,name); _Arg(Symbol*,symbol);
            View(name, symbol);
        } break;
        case 259: { _Arg(b8,boolean); _Arg(Array_Fn_Call_P,thenBlock); _Arg(Array_Fn_Call_P,elseBlock);
            If(boolean, thenBlock, elseBlock);
        } break;
        case 260: { _Out(b8); _Arg(b8,boolean);
            *c_out = Not(boolean);
        } break;
        case 261: { _Arg(Fn_Call*,condition); _Arg(Array_Fn_Call_P,body);
            While(condition, body);
        } break;
        case 262: { _Arg(String,iterName); _Any(weaArray); _Arg(Foreach_State*,state);
            Foreach_Begin_(iterName, weaArray, state);
        } break;
        case 263: { _Arg(Foreach_State*,state);
            Foreach_Update(state);
        } break;
        case 264: { _Arg(String,iterName); _Any(array); _Arg(Array_Fn_Call_P,body);
            Foreach(iterName, array, body);
        } break;
        case 265: { _Any(out); _Arg(String,typeName); _Any(src);
            Cast(out, typeName, src);
        } break;
        case 266: { _Any(wArray); _Any(elem);
            WArray_Push(wArray, elem);
        } break;
        case 267: { _Any(out); _Any(wArray); _Arg(u32,index);
            WArray_Index(out, wArray, index);
        } break;
        case 268: { _Out(String); _Arg(Type*,type);
            *c_out = Type_Get_Name(type);
        } break;
        case 269: { _Out(u32); _Arg(u32,a); _Arg(u32,b);
            *c_out = Mul(a, b);
        } break;
        case 270: { _Out(u32); _Arg(u32,a); _Arg(u32,b);
            *c_out = Add(a, b);
        } break;
        case 271: { _Out(u32); _Arg(u32,a); _Arg(u32,b);
            *c_out = Sub(a, b);
        } break;
        case 272: { _Out(b8); _Any(a); _Any(b);
            *c_out = Eq(a, b);
        } break;
        case 273: { _Out(b8); _Arg(u32,a); _Arg(u32,b);
            *c_out = Less_Than(a, b);
        } break;
        case 274: {
            Return();
        } break;
        case 275: { _Arg(String,path); _Arg(String,alias); _Arg(b8,using);
            Import(path, alias, using);
        } break;
        case 276: { _Out(String);
            *c_out = Input();
        } break;
        case 277: { _Var(args, 0);
            Output(args);
        } break;
        case 278: { _Out(String); _Arg(u32,value);
            *c_out = Str_From_U32(value);
        } break;
        case 279: { _Out(String); _Arg(String,fmt); _Var(args, 2);
            *c_out = WStr_From_Fmt(fmt, args);
        } break;
        case 280: { _Any(dst); _Any(src);
            Transfer(dst, src);
        } break;
        case 281: { _Any(out); _Var(args, 1);
            Lit(out, args);
        } break;
        case 282: { _Out(Fn_Call*); _Var(inArgs, 1);
            *c_out = Fn_Call_Create(inArgs);
        } break;
        case 283: { _Out(b8); _Arg(Type*,type);
            *c_out = Type_Has_Pointer_Rec(type);
        } break;
        case 284: { _Out(Realloc_Error); _Arg(u8*,inAddress); _Arg(Realloc_State*,state);
            *c_out = Realloc(inAddress, state);
        } break;
        case 285: { _Any(var); _Arg(b8,recursive); _Arg(b8,isArrayElem); _Arg(b8,stringBefore); _Arg(u32,depthLevel);
            Serialize_Rec(var, recursive, isArrayElem, stringBefore, depthLevel);
        } break;
        case 286: { _Out(Symbol*); _Arg(Symbol**,iter); _Arg(Type*,type); _Arg(u8*,ptr);
            *c_out = Util_Iter(iter, type, ptr);
        } break;
        case 287: { _Arg(String,path);
            Wea_Save(path);
        } break;
        case 288: { _Arg(String,path);
            Wea_Load(path);
        } break;

        NO_DEFAULT
    }
}

